version: '3'

services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    runtime: nvidia
    ports:
      - "8000:8000" 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:testpass123@db:5432/postgres
      - ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173 
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./data:/app/data
      - .:/app

volumes:
  postgres_data: